spring.datasource.url=jdbc:mysql://localhost:3306/carlib?useUnicode=true&characterEncoding=utf8 
spring.datasource.username=root
spring.datasource.password=Sql_pas_314
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver

blog.title=DevPub
#"subtitle": "???????? ?????????????",
#"phone": "+7 903 666-44-55",
#"email": "mail@mail.ru",
#"copyright": "??????? ???????",
#"copyrightFrom": "2005"